data<-read.table("household_power_consumption.txt",sep=";",header=TRUE,na.strings="?",stringsAsFactors = FALSE)
library(lubridate)
data$Date<-dmy(data$Date)
date1=as.Date("2007/02/01")
date2=as.Date("2007/02/02")
df<-subset(data,data$Date>=date1&data$Date<=date2)
df$DateTime<-as.POSIXct(paste(df$Date,df$Time))
png("plot3.png", width=480, height=480)
plot(df$DateTime,as.numeric(df$Sub_metering_1),type="l",ylab="Energy sub metering",xlab="")
lines(df$DateTime,as.numeric(df$Sub_metering_2),col="red")
lines(df$DateTime,as.numeric(df$Sub_metering_3),col="blue")
legend('topright', names(df)[7:9],lty=1, col=c('black', 'red', 'blue'), cex=.75)
dev.off()
