data<-read.table("household_power_consumption.txt",sep=";",header=TRUE,na.strings="?",stringsAsFactors = FALSE)
library(lubridate)
data$Date<-dmy(data$Date)
date1=as.Date("2007/02/01")
date2=as.Date("2007/02/02")
df<-subset(data,data$Date>=date1&data$Date<=date2)
png("plot1.png", width=480, height=480)
hist(as.numeric(df$Global_active_power), col="red", main="Global Active Power", xlab="Global Active Power (kilowatts)")
dev.off()