data<-read.table("household_power_consumption.txt",sep=";",header=TRUE,na.strings="?",stringsAsFactors = FALSE)
library(lubridate)
data$Date<-dmy(data$Date)
date1=as.Date("2007/02/01")
date2=as.Date("2007/02/02")
df<-subset(data,data$Date>=date1&data$Date<=date2)
df$DateTime<-as.POSIXct(paste(df$Date,df$Time))
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2))
plot(df$DateTime,as.numeric(df$Global_active_power),type="l",ylab="Global Active Power (kilowatts)",xlab="")
plot(df$DateTime,as.numeric(df$Voltage),type="l",ylab="Voltage",xlab="datetime")
plot(df$DateTime,as.numeric(df$Sub_metering_1),type="l",ylab="Energy sub metering",xlab="")
lines(df$DateTime, df$Sub_metering_2, col = 'red')
lines(df$DateTime, df$Sub_metering_3, col = 'blue')
plot(df$DateTime,as.numeric(df$Global_reactive_power),type="l",ylab="Global_reactive_power",xlab="datetime")
dev.off()
